Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	ScrapeGC
	1

[Thu Nov 19 16:17:06 2020]
rule ScrapeGC:
    input: data/gc-list-filtered.csv
    output: data/gc-scrape.csv
    jobid: 0

[Thu Nov 19 16:17:07 2020]
Error in rule ScrapeGC:
    jobid: 0
    output: data/gc-scrape.csv

RuleException:
CalledProcessError in line 41 of /home/adrian/PhD-Laptop/Pd_Geocache/workflow/snakefile:
Command 'set -euo pipefail;  /home/adrian/anaconda3/bin/python3.7 /home/adrian/PhD-Laptop/Pd_Geocache/workflow/.snakemake/scripts/tmp8rnjs9i5.pycaching.py' returned non-zero exit status 1.
  File "/home/adrian/anaconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2252, in run_wrapper
  File "/home/adrian/PhD-Laptop/Pd_Geocache/workflow/snakefile", line 41, in __rule_ScrapeGC
  File "/home/adrian/anaconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/adrian/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/home/adrian/anaconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/adrian/anaconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2264, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/adrian/PhD-Laptop/Pd_Geocache/workflow/.snakemake/log/2020-11-19T161706.536491.snakemake.log
